language: ruby
rvm:
- 2.1
install: gem install jekyll html-proofer
script: jekyll build && htmlproof ./_site --disable-external

branches:
  only:
  - gh-pages
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
